### ISSUE TITLE
Your example doc does not work.

### ISSUE THREAD

**Issue by MathisonProjects** [elibyy/laravel-tcpdf#1]
I put in the required file.

I inserted the provider you gave.

I ran composer update.

I attempted to create a file.

An error is not thrown, but it ceases working for some reason.

If you need a deeper explanation or demonstration of what I am doing so you can improve this package, do let me know.

Thanks!

**Comment by elibyy** [comment]
hey i need further info of the error you are receiving i'm sorry i somehow github didn't notified me about this issue

**Comment by MathisonProjects** [comment]
Hey, I can show you the error when I get home from work. I'm living in
central time, and should be home at 5:30. What time is good for you?

On Mon, Mar 16, 2015 at 10:18 AM, elibyy notifications@github.com wrote:

> hey i need further info of the error you are receiving i'm sorry i somehow
> github didn't notified me about this issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elibyy/laravel-tcpdf/issues/1#issuecomment-81729493.

## 

---

5129 Eastridge Dr
Omaha NE 68134
1 (402) 417 - 2122
jakethewizard04@gmail.com
mathison.jacob@gmail.com

**Comment by elibyy** [comment]
i'm on IST (israel standard time) which is GMT+3 so i'm available from 10 to 5 my time but you could also use the gitter i opened to communicate also i should be available in the few hours

**Comment by MathisonProjects** [comment]
Darn time zones... so I'll put up a video.at my first convenience.

**Comment by MathisonProjects** [comment]
Also found another fun bug...

Your package also suppresses debug messages. You might want to look into that.

**Comment by elibyy** [comment]
i cant seem to see that it suppresses errors

**Comment by MathisonProjects** [comment]
Probably related/similar issue.

Again, when I have a chance, I'll show you.

**Comment by elibyy** [comment]
currently closing as you haven't sent any error details
