### ISSUE TITLE
Help guide needs an update...

### ISSUE THREAD

**Issue by MathisonProjects** [elibyy/laravel-tcpdf#11]
Dug into your code and saw some minor changes that are required in order for people to use your PDF tool.

Code is as follows:

use TCPDF;

$pdf = new TCPDF;
$pdf->SetTitle('Hello World');
$pdf->AddPage();
$pdf->Write(0, 'Hello World');
$pdf->Output('hello_world.pdf','D');

**Comment by elibyy** [comment]
Hey. My tool is a wrapper for tcpdf. If you want to use tcpdf directly. There's no need of my code :)
