### ISSUE TITLE
Error when triggering the generation of multiple PDF's one after another.

### ISSUE THREAD

**Issue by chrislentz** [elibyy/laravel-tcpdf#12]
I have a Laravel command that syncs items (including generated pdf's) to a third party service via API. If there is only one PDF to generate, it runs fine, but if I have 2 items to sync, the command fails on the second PDF generation.

```
[ErrorException]
Undefined property: Elibyy\TCPDF\TCPdf::$h
```

I can't post my PDF generation code because I have secure business logic intertwined to generate the PDF. Do I need to have something at the end of the generation that resets TCPDF?

**Comment by elibyy** [comment]
fixed in https://github.com/elibyy/laravel-tcpdf/releases/tag/v0.0.4

if it's suites you close the issue :+1:

**Comment by chrislentz** [comment]
I am now seeing this error:

```
[ErrorException]
Undefined property: TCPDF::$h
```

**Comment by elibyy** [comment]
as mentioned in the release. there's a new method called reset. you should do 

``` php
foreach($x as $y){
  PDF::reset();
  //rest of logic
}
```

**Comment by chrislentz** [comment]
That did it. Thanks for clearing that up and for adding the new functionality.

**Comment by geetubabu** [comment]
i am getting an error Undefined property: Elibyy\TCPDF\TCPDFHelper::$inxobj while generation of multiple PDF's

**Comment by elibyy** [comment]
Hey @geetubabu,
Please note: this library is abandoned in favor of the [new one](https://github.com/elibyy/tcpdf-laravel).
So if this issue still happens in the new library please open a new issue there.
Thanks
