### ISSUE TITLE
Class 'PDF' not found

### ISSUE THREAD

**Issue by matuuz** [elibyy/laravel-tcpdf#13]
Class 'PDF' not found

**Comment by elibyy** [comment]
hey there, which version have you used, have you added the alias to your config/app.php as described [here](https://github.com/elibyy/laravel-tcpdf/blob/5.1/README.md)

**Comment by matuuz** [comment]
Working great man! i don't remember watching this at the guide, maybe you should add some links to other laravel versions. Thank you for your help!

**Comment by mcpDeveloper** [comment]
Hi i was having this error, followed the instruction and now i get Trait PDF not found.. :/
