### ISSUE TITLE
Does this wrapper has UTF8 support

### ISSUE THREAD

**Issue by bczm8703** [elibyy/laravel-tcpdf#15]
my code to load the pdf
 `     $html = view('sample_pdf');

```
    PDF::SetTitle('My Test Page');

    PDF::AddPage();

    PDF::writeHTML($html);

    PDF::Output('sample.pdf');
```

`
html code

![screen shot 2015-09-09 at 10 11 39 am](https://cloud.githubusercontent.com/assets/8233066/9751753/32b96248-56db-11e5-961e-ab49e100db84.png)

the chinese words are being replace with "?"

PDF output
![screen shot 2015-09-09 at 10 12 27 am](https://cloud.githubusercontent.com/assets/8233066/9751762/5363628c-56db-11e5-97c7-b85669a9f0ff.png)

**Comment by elibyy** [comment]
hey you should read [this](http://www.tcpdf.org/fonts.php)
