### ISSUE TITLE
SetHeaderData

### ISSUE THREAD

**Issue by hubentom** [elibyy/laravel-tcpdf#18]
seemed to be working and now this command is not? not seeing a header is my PDFs

**Comment by elibyy** [comment]
hey there,
can you elaborate on the error you encountering, i can't understand

**Comment by hubentom** [comment]
using setHeaderData - i get no header in my document anymore

**Comment by hubentom** [comment]
have you had a chance to look at setHeaderData?

**Comment by elibyy** [comment]
I'm sorry but I'm not very familiar with all the functionality of TCPDF library. so I think that the methods I've added that override the `header` | `footer` methods might have conflicted them.
 so you should try using this instead . `PDF::setHeaderCallback(function($pdf){})`

**Comment by hubentom** [comment]
I will try that but... dont you think you should run thru their basic examples in test before releasing a change potentially breaking your component?

**Comment by saaiful** [comment]
`PDF::setHeaderCallback(function ($pdf) {
$pdf->Write(0, "page title", '', 0, 'L', true, 0, false, false, 0);
});`

Using this you can set custom header

**Comment by elibyy** [comment]
this repository is being abondend you can visit the new one [here](https://github.com/elibyy/tcpdf-laravel)
