### ISSUE TITLE
5.2 support

### ISSUE THREAD

**Issue by j-hernandez** [elibyy/laravel-tcpdf#21]
Would it be possible to have a branch for 5.2 support?

As far as I can tell, the changes required would be:
- illuminate/support @ 5.2.*
- tcpdf @ 6.2.12

And changing ServiceProvider.php#L30 from 
`$this->app->bindShared`
to
`$this->app->singleton`

Still testing in my app. I can try to fix up a PR if you want.

**Comment by Silvio8** [comment]
I'm also locking for a good solution

**Comment by elibyy** [comment]
hey, ill look into it, i'm thinking of resetting this repo and re-branching it so that the old one (5.0) will not be master will notify

**Comment by j-hernandez** [comment]
@elibyy awesome. Thanks!

**Comment by elibyy** [comment]
https://github.com/elibyy/tcpdf-laravel

**Comment by Silvio8** [comment]
installion still not working with stable config

**Comment by Silvio8** [comment]
I get the following error:
Loading composer repositories with package information 
Updating dependencies (including require-dev) 
Your requirements could not be resolved to an installable set of packages. 
Problem 1 
    - Conclusion: don't install laravel/framework 5.2.x-dev 
    - Conclusion: remove laravel/framework v5.2.14 
    - Conclusion: don't install laravel/framework v5.2.14 
    - Conclusion: don't install laravel/framework v5.2.13 
    - Conclusion: don't install laravel/framework v5.2.12 
    - Conclusion: don't install laravel/framework v5.2.11 
    - Conclusion: don't install laravel/framework v5.2.10 
    - Conclusion: don't install laravel/framework v5.2.9 
    - Conclusion: don't install laravel/framework v5.2.8 
    - Conclusion: don't install laravel/framework v5.2.7 
    - Conclusion: don't install laravel/framework v5.2.6 
    - Conclusion: don't install laravel/framework v5.2.5 
    - Conclusion: don't install laravel/framework v5.2.4 
    - Conclusion: don't install laravel/framework v5.2.3 
    - Conclusion: don't install laravel/framework v5.2.2 
    - Conclusion: don't install laravel/framework v5.2.1 
    - Conclusion: don't install laravel/framework v5.2.0 
    - elibyy/tcpdf-laravel 5.1.0 requires illuminate/support 5.1.x -> satisfiable by illuminate/support[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8]. 
    - elibyy/tcpdf-laravel 5.1.x-dev requires illuminate/support 5.1.x -> satisfiable by illuminate/support[5.1.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8]. 
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.0-beta1 
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.0-beta1 
    - Installation request for laravel/framework 5.2.\* -> satisfiable by laravel/framework[5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9]. 
    - Installation request for elibyy/tcpdf-laravel 5.1.\* -> satisfiable by elibyy/tcpdf-laravel[5.1.0, 5.1.x-dev].

**Comment by elibyy** [comment]
You should try to specify the exact version 5.1.0/5.2.0 or set minimum stability to stable or add prefer stable
