### ISSUE TITLE
Custom header and footer

### ISSUE THREAD

**Issue by infoshahin** [elibyy/laravel-tcpdf#22]
How can I use custom header or footer Using this package?

```
`use PDF;

PDF::SetTitle('Hello World');

PDF::AddPage();

PDF::Write(0, 'Hello World');

PDF::Output('hello_world.pdf');`
```

It work fine, but I can’t add custom header and footer!

**Comment by elibyy** [comment]
please check out this issue #14 also check the README for instructions about the new repository

**Comment by infoshahin** [comment]
Ok I'll check it.
