### ISSUE TITLE
Persian language is not supported!

### ISSUE THREAD

**Issue by hbsoftco** [elibyy/laravel-tcpdf#23]
Hi
How do I save my file with the Persian language?
Persian character displayed with ?????
help me please

**Comment by elibyy** [comment]
hey there,
the problem you are addressing in related to the TCPDF and not tho my wrapper, but try this [font](https://github.com/ooghry/TCPDF-Persian-Farsi-font)

**Comment by reza-hm89** [comment]
hi
This package does not support Persian language, you can using laravel-tcpdf package.
package link: https://github.com/elibyy/laravel-tcpdf
