### ISSUE TITLE
Undefined property: Elibyy\TCPDF\Pdf::$inxobj

### ISSUE THREAD

**Issue by ahmednumaan** [elibyy/laravel-tcpdf#5]
Getting this error in the following function:
ErrorException in tcpdf.php line 3103:
Undefined property: Elibyy\TCPDF\Pdf::$inxobj

public function pdf_order($data, $order_id) {
        ob_start();
        //$this->getGenerateAffair($order_id);
        $pdf = new PDF($orientation = 'P', $unit = 'in', $format = 'A4', $unicode = true, $encoding = 'UTF-8', $diskcache = false, $pdfa = false);
        $pdf::SetPrintHeader(false);
        $pdf::SetPrintFooter(false);
        $pdf::AddPage();
        $pdf::setHtmlVSpace(array('p' => array(array('n' => 0.01), array('n' => 0.01))));
        $html = view('app.pdf.order/en_p1', $data)->render();
        $pdf::writeHTML($html, true, false, true, false, '');

```
    $pdf::AddPage();
    $html = view('app.pdf.order/en_p2', $data)->render();
    $pdf::writeHTML($html, true, false, true, false, '');
    $pdf::lastPage();
    $path = "./pdf/affairs/" . $order_id;
    if (file_exists($path) == false) {
        File::makeDirectory($path, $mode = 0777);
    }
    $pdf::Output(__DIR__ . '\..\..\..\public\pdf\affairs\\' . $order_id . '\\' . $order_id . '_affar.pdf', 'F');
    ob_end_clean();
    return;
}
```

**Comment by elibyy** [comment]
this problem seems to be related to tcpdf itself
