### ISSUE TITLE
how to load blade view ?

### ISSUE THREAD

**Issue by yogevLevi** [elibyy/laravel-tcpdf#6]
Is there a way to load view and passing data to the view?

 something like
$pdf = new TCPDF()
$pdf->SetPrintHeader(false);
$pdf->SetPrintFooter(false);
$pdf ->loadView('pdf.invoice', $data);
$pdf->Output(storage_path().'/pdf/file.pdf', 'I');

thanks.

**Comment by elibyy** [comment]
take a look at [this](http://www.tcpdf.org/doc/code/classTCPDF.html#ac3fdf25fcd36f1dce04f92187c621407) so then you can use `PDF::writeHtml(view('pdf.invoice',$data))`

**Comment by yogevLevi** [comment]
i have a form of 20 pages writing in laravel blade when my client fill the form and click submit i want to generate pdf for him and save it

i try to do it like this in my controller

public function createPDF()
{
    $pdf = Input::get('pdf',null);
    $company = Input::get('company',null);
    $branch = Input::get('branch',null);
    $sub_branch = Input::get('sub_branch',null);
    $form_type = Input::get('form_type',null);
    $form_name = Input::get('form_name',null);
    $form_heb_name = Input::get('form_heb_name',null);
    $sig_path=FormsController::getSignature_file();

$data=compact('company','branch','sub_branch','form_type','form_name','form_heb_name','sig_path');
    Input::flash();
    if ($pdf) 
        { 
            $pdf = new TCPDF();
            $pdf->SetPrintHeader(false);
            $pdf->SetPrintFooter(false);
            $pdf->AddPage();
            $pdf->writeHTML(view('forms.'.$company.'.'.$branch.'.'.$sub_branch.'.'.$form_type.'.'.$form_name, $data)->render());
            $filename = storage_path().'/forms_pdf/10006/26/4718326/'.$form_name.'.pdf';
            $pdf->output($filename, 'I');
            return redirect('forms');
        }
     return view('forms.'.$company.'.'.$branch.'.'.$sub_branch.'.'.$form_type.'.'.$form_name , $data);
}
bat its not working it's create 2 pdf page with All fields on top of each other

how to fix it?

In addition, I want to save the pdf in a way it can not be edited file how can i do it?

thanks.

**Comment by elibyy** [comment]
sorry for the delay. but it seems that the error is unrelated to my wrapper. but to the actual TCPDF you should try to read their documentation etc...
